### ISSUE TITLE
Quotes are not handled when reading Rofi command from configuration file

### ISSUE THREAD

**Issue by HactarCE** [cspeterson/splatmoji#11]
My configuration file at `~/.config/splatmoji/splatmoji.config`:
```
rofi_command=rofi -dmenu -p '' -i -font "Roboto Mono 14"
```

**Expected behavior**
- `''` should be interpreted as a single blank argument
- `"Roboto Mono 14"` should be interpreted as a single argument `Roboto Mono 14`
- Rofi runs with a blank prompt (`-p ''`) and using the font Roboto Mono (`-font "Roboto Mono 14"`)

**Actual behavior**
- `''` is interpreted literally as the two-character argument `''`
- `"Roboto Mono 14"` is interpreted as three arguments: `"Roboto`, `Mono`, and `14"`
- Rofi errors, complaining that it cannot find the font `"Roboto`

Furthermore, backslash escapes do not work. For example, `Roboto\ Mono\ 14` is interpreted as three arguments: `Roboto\`, `Mono\`, and `14`.

**Comment by cspeterson** [comment]
Thanks! You made me realize another odd problem along the way so we have two commits as a result of this issue: e34fb3a, 4a1b63c

**Comment by cspeterson** [comment]
And now I realize that I forget how rofi works first commit didn't fix anything, so putting it back: 858da86

your quote interpolation should be good though! 🙂

**Comment by HactarCE** [comment]
Thank you very much for the quick response and fix! :+1:
