### ISSUE TITLE
Some emoji's are not rendering

### ISSUE THREAD

**Issue by razvan-flavius-panda** [cspeterson/splatmoji#14]
![](https://i.imgur.com/wDWkJZv.png)

I'm using NixOS 19.03 / Linux.

**Comment by cspeterson** [comment]
On the face if it this looks to me like a font issue, though what font would have the rest of those but *not* `😬` I don't know. Noto emoji seem to be available for NixOS from my cursory search.

Are you able to render these emoji on the CLI in general?

Here's a way to output grimace just by its hex code:

`echo -e "\U1F62C"`

Does that work for you by itself?

**Comment by razvan-flavius-panda** [comment]
@cspeterson `echo -e "\U1F62C"` does not work, it renders as a `😬`.

**Comment by cspeterson** [comment]
Okay then! It does look like an issue between you and your distro and font configuration. If the system can't render the emoji, neither can this application. 🙂

I found [this page](https://nixos.wiki/wiki/Fonts) about font packages on NixOS, if that helps, and I'd like to hear if you get it working 😁

**Comment by razvan-flavius-panda** [comment]
@cspeterson I tried many fonts and none worked perfectly:

    noto-fonts-emoji

rendered the fonts hugely so they do not fit in the UI and I think it also removes their description:

![](https://i.imgur.com/hCxD2xZ.png)

But the good part with this `noto-font-emoji` is that it rendered ALL of the fonts it seems.

While the fonts `emojione` and `rPackages.emojifont` only renderednd a few additional emoji's and not all of them.

I think you need to implement some way in your application to scale the font size properly for `noto-fonts-emoji` on NixOS / Linux and that would solve the problem.

I do not understand why you close the issue, since the problem is not solved.

**Comment by cspeterson** [comment]
I closed the issue because it sure sounded like an issue with elements outside the control of this application, but we canv take a deeper look 🙂

Maybe there are some rofi options that we can fiddle with or something

So I'd say take a look at how fonts are rendering in your applications in general again. Do these symbols render all huge in the cli? Try manually outputting the grimacing emoji again:

`echo -e "\U1F62C"`

If it's huge in your normal terminal though then I think, again, this is outside of our scope here ☹️

**Comment by razvan-flavius-panda** [comment]
@cspeterson when I used the `noto-fonts-emoji` the fonts were only rendered hugely in the GUI and not when I actually when I pressed enter so that they would be showed, they were showed at correct size.

Also note the missing of the descriptions for the huge emojis, that is definitely an issue with `splatmoji`.

**Comment by iFreilicht** [comment]
@razvan-flavius-panda have you tried copying these emoji into your regular rofi prompt and checking if they render there correctly? I believe this could be a problem with your rofi config.

**Comment by razvan-flavius-panda** [comment]
@iFreilicht I do not know what a rofi prompt is.

**Comment by iFreilicht** [comment]
This tool uses [rofi](https://github.com/davatorium/rofi) to display its UI. It's normally an app launcher/window switcher, but very extensible. You can start it like so:

    rofi -show run

Use splatmoji first to put some of those not properly printing characters into a text file, then copy then.
After that, run rofi as shown above and paste the characters into its prompt. If they don't render there either, the fault is either with rofi or your font.

If you don't know about rofi, how did you manage to make the `noto` fonts work? Normally, this requires you to edit `.config/rofi/config.rasi`.

**Comment by razvan-flavius-panda** [comment]
> If you don't know about rofi, how did you manage to make the noto fonts work?

If I remember correctly I installed the fonts using Nix and that got them used.

I might check what you mentioned later, currently I have other priorities.

**Comment by cspeterson** [comment]
I'm sorry I still haven't accomplished my intention of installing Nix and trying to reproduce this

but like @iFreilicht was saying, this application uses `rofi` for its menu and testing by calling rofi directly from the cli could reveal something

```sh
# This will populate the menu with just grimace face and party face emoji similar to their presentation in splatmoji
echo -e "\U1F62C\tsome,words\n\U1f973\tsome,more,words" | rofi -dmenu
```

I think I saw party face being huge in your screenshot so I included it in the test. 🥳

**Comment by razvan-flavius-panda** [comment]
Anything you would like me to test for this issue?

**Comment by cspeterson** [comment]
Indeed! The code snippet from above

```
echo -e "\U1F62C\tsome,words\n\U1f973\tsome,more,words" | rofi -dmenu
```
