### ISSUE TITLE
History doesn't seem to work

### ISSUE THREAD

**Issue by farzadmf** [cspeterson/splatmoji#26]
Hi,

First of all, thank you for what you've done. I seem to have problems making history work. This is my config:
```config
history_file=~/.config/splatmoji/history
history_length=10
rofi_command=rofi -dmenu -p splatmoji -i -theme purple -columns 2 -drun-match-fields categories -matching fuzzy -sorting-method levenshtein
xdotool_command=xdotool sleep 0.2 type --delay 100
xsel_command=xsel -b -i
```

I think the history is supposed to be shown at the top, but I don't see anything.

**Comment by cspeterson** [comment]
Whoops! Sorry, this is my fault - a bad example provided inside the config file.

Fix is simple: be explicit for the history file path, as the tilde will not be expanded. E.g. `history_file=/home/myusername/path/to/thing`

Let it be noted that @WPettersson was 100% when he pointed this out as a problem and I just failed to clean it up before it caught you. I'll be pushing a correction shortly! 😇

**Comment by farzadmf** [comment]
Thank @cspeterson  for your reply. I tried to full path, and it doesn't seem to change anything :slightly_frowning_face: 

I guess there's no need for a "restart" or something, right? Every time I start `splatmoji`, it should read the updated config file, right?

I also tried to create the file manually, but the history isn't showing up

**Comment by farzadmf** [comment]
Yup, it shows this:
```
# Config:
# Config:
'history_length': '10'
'xdotool_command': 'xdotool sleep 0.2 type --delay 100'
'history_file': '/home/farzad/.config/splatmoji/history'
'xsel_command': 'xsel -b -i'
'rofi_command': 'rofi -dmenu -p splatmoji -i -theme DarkBlue -columns 2 -drun-match-fields categories -matching fuzzy -sorting-method levenshtein'
h
```

**Comment by WPettersson** [comment]
Okay ... I don't know why history_file wouldn't work then. Can you try either applying https://gist.github.com/WPettersson/3f1e2384e029aeb8044221779c1b6da0, or adding debug prints to both branches of the `if` on line 41?

Actually, just to check, are you running the latest git version of splatmoji, or a packaged version from somewhere?

**Comment by farzadmf** [comment]
I'm gonna try the patch in a bit, but about the package, I'm using the [`splatmoji-git` AUR package](https://aur.archlinux.org/packages/splatmoji-git), so I'm guessing it should be the latest git version

**Comment by WPettersson** [comment]
That does sound like an old version. If you re-build the AUR package (run makepkg again with appropriate options) it should download the latest git once more.

**Comment by farzadmf** [comment]
Hey @WPettersson , I re-installed the package, and the history seems to be working fine now 🙂

Just one suggestion: I think it's a good idea to have a history similar to what `rofimoji` has, where it shows a separate row of history, along with shortcuts `alt + 0 ... 9` to enter them

I'm gonna close this since it doesn't seem to be an issue with the latest result

**Comment by cspeterson** [comment]
@farzadmf first of all I didn't know about rofimoji before this moment so thanks for sharing! 🙂

So I'll make myself more familiar and have a think about changing the UI operations, thanks!

**Comment by cspeterson** [comment]
PS I have no idea how AUR works nor do I know who created that out-of-date one

I'm totally open to making Pacman packages though, as it appears that it is a supported for fpm (by the packing tool I'm currently using) so lemmee see what I can do 😉

**Comment by cspeterson** [comment]
and @WPettersson ty for sorting this out! 😅
