### ISSUE TITLE
Keyboard bindings broken while splatmoji is open

### ISSUE THREAD

**Issue by BackSlasher** [cspeterson/splatmoji#3]
Apologies for being a GUI noob.
Just found splatmoji, really hits the spot 😃
I have Arch with i3wm.
When running `splatmoji -copy` or `splatmoji -type`, while the splatmoji window is open, my PrintScreen keybind is broken. Other keybinds (e.g. volume mute) are broken as well.
Is it possible that splatmoji is swallowing all keys, instead of just regular letter inputs?

Thanks!

**Comment by BackSlasher** [comment]
Probably DaveDavenport/rofi#301

**Comment by cspeterson** [comment]
I have much the same experience with my scripts that use the related utility dmenu. Looks like it's out of our hands.

Thanks for trying to help though! 🙂
