### ISSUE TITLE
Switch between "type" and "copypaste" depending on active window

### ISSUE THREAD

**Issue by jpetazzo** [cspeterson/splatmoji#30]
Hi!

First, thanks for writing splatmoji; it's my favorite emoji input method (and I tried a bunch of them😅).

On my machine, the `type` doesn't work on Firefox; and the `copypaste` method doesn't work in my terminal, because my terminal requires `Ctrl+Shift+v` to paste. I can't use `Ctrl+Shift+v` to paste in Firefox because it triggers one of my extensions.

So I came up with the following helper script, which I called `autosplatmoji`:

```bash
#!/bin/sh
WINDOWNAME="$(xdotool getwindowfocus getwindowname)"
case "$WINDOWNAME" in
  *Firefox*)
  exec splatmoji copypaste ;;
  *)
  exec splatmoji type ;;
esac
```

Of course, other apps can be added to the "exception" list, and the logic could be reversed (i.e. use `splatmoji copypaste` by default, except for some apps). It's not bullet-proof either; example: the title of my shell windows is my `PS1` variable, which contains the current directory; so if I am in a directory containing the string `Firefox` it won't work. But it covers 99% of my use cases.

What would be best?
- should I try to submit a PR to add this behavior natively in splatmoji? (Maybe with a `splatmoji auto` mode, and a configuration entry to specify strings to look for to switch to copypaste mode?)
- should I just add this helper script and/or some documentation in the README?
- should we not bother, and just close this issue, since it's already (hopefully) useful for other folks with the same problem?

Cheers!

**Comment by cspeterson** [comment]
I'm leaning towards this being a tip for the README. Maybe in the FAQ under "How do I handle different paste keys between terminal emulators and GUI applications?"

Good thinking though and I'm glad to have it documented!

**Comment by cspeterson** [comment]
There isn't a good way to identify a window as a terminal emulator *in general* is there? Just poking at different ones with `xprop` I'm not seeing any properties that could make the distinction across the board :/

**Comment by jpetazzo** [comment]
Not that I'm aware of, alas!

Let me know if you'd like me to take a stab at a PR for the README, or if you're more comfortable incorporating it yourself to fit your own style etc (you are of course more than welcome to use/adapt/whatever the wording I've put above).

Thanks either way!

(And if some day I come up with an even better solution, I'll report back :))

**Comment by cspeterson** [comment]
@jpetazzo I've added it to the README! 😁

https://github.com/cspeterson/splatmoji/commit/2eb2e22a33feecf7f2b2888e95427b83086e9546
