### ISSUE TITLE
Allow disabling all skin tones

### ISSUE THREAD

**Issue by vicnett** [cspeterson/splatmoji#35]
If I never use any of the `--skin-tones` versions of emoji, having them always show up in my searches is very cluttered.

I can choose an arbitrary skin tone to reduce the clutter, but ideally I'd like an option to completely remove all skin tone versions.

**Comment by cspeterson** [comment]
Yes that's probably not a bad idea

I think I can implement this without too much refactoring, probably by allowing `--skin-tones none` or somesuch

another possibility is a new flag to just ignore all tones, period

I'll have to see! 🙂

**Comment by cspeterson** [comment]
#36 is now in the main branch, enabling this new behavior by `--skin-tones none` 👍️

**Comment by vicnett** [comment]
Dang that was _fast_! Thanks!
